development:
  adapter: mysql2
  database: myapp_development
  pool: 20
  encoding: utf8
  username: Leo
  password:  XPmMxZf
  host:  localhost:3000

test:
  adapter: mysql2
  database: myapp_test
  pool: 20
  encoding: utf8
  username: user
  password: password
  host:  localhost

production:
  adapter: mysql2
  database: myapp
  pool: 20
  encoding: utf8
  username: leo
  password:  XPmMxZf
  host: https://smartparking2.herokuapp.com
